name = "Geppaku"
license = "MIT"
licenselink = "https://github.com/koooge/hugo-theme-geppaku/blob/master/LICENSE.md"
description = "Geppaku is bluish white theme for Hugo"
homepage = "https://github.com/koooge/hugo-theme-geppaku"
tags = ["blog", "personal"]
features = ["blog"]
min_version = 0.67

[author]
  name = "The Geppaku Authors"
  homepage = "http://koooge.com/"
